version: "3.6"

services:
  nginx:
    image: tarantool/tarantool-nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf 
    network_mode: host

  clickhouse-server:
    image: yandex/clickhouse-server
    volumes:
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - clickhouse:/var/lib/clickhouse
    depends_on:
      - kafka
    links: 
      - kafka
    ports:
      - 8123:8123

  clickhouse-client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    volumes:
      - kafka:/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    depends_on:
      - zookeeper  
    links: 
     - zookeeper
    ports:
     - 9092:9092
     - 9094:9094

  zookeeper:
    image: zookeeper
    volumes:
      - zookeeper:/data
    ports:
      - 2181:2181

volumes:
  clickhouse:
  zookeeper:
  kafka:
