{
 "title": "IoT Cloud - Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Device01",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "dev01", "type": "timeseries" }
   ]
  },
  {
   "title": "Device02",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "dev02", "type": "timeseries" }
   ]
  },
  {
   "title": "Device03",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "dev03", "type": "timeseries" }
   ]
  },
  {
   "title": "Device04",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "dev04", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 01 (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "dev01", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 01",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "dev01", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 02",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "dev02", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 02 (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "dev02", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 03 (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "dev03", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 03",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "pressure" }
   ],
   "targets": [
    { "target": "dev03", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 04",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "pressure" }
   ],
   "targets": [
    { "target": "dev04", "type": "timeseries" }
   ]
  },
  {
   "title": "Device 04 (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "dev04", "type": "timeseries" }
   ]
  }
 ]
}