{
 "title": "IoT Cloud - BI Analytics",
 "time": { "from": "1970-01-01T00:00:00.001Z", "to": "1970-01-01T00:00:00.056Z" },
 "panels": [
  {
   "title": "Count telemetry for last 7 day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count() as requests,\n    toDate(timestamp)\nFROM telemetry\nWHERE\n    timestamp BETWEEN toStartOfInterval(now(), INTERVAL 7 day)\n    AND now()\nGROUP BY toDate(timestamp)",
     "rawQuery": "SELECT     count() as requests,     toDate(timestamp) FROM telemetry WHERE     timestamp BETWEEN toStartOfInterval(now(), INTERVAL 7 day)     AND now() GROUP BY toDate(timestamp)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count telemetry by cities for last 7 day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count(),\n    city\nFROM telemetry\nWHERE\n    timestamp BETWEEN toStartOfInterval(now(), INTERVAL 7 day)\n    AND now()\nGROUP BY city",
     "rawQuery": "SELECT     count(),     city  FROM telemetry WHERE timestamp BETWEEN toStartOfInterval(now(), INTERVAL 7 day)  AND now() GROUP BY city",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count telemetry by cities in all time",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count() as requests,\n    city\nFROM telemetry\nGROUP BY city",
     "rawQuery": "SELECT     count() as requests,     city FROM telemetry GROUP BY city",
     "round": "0s"
    }
   ]
  },
  {
   "title": "TOP 5 - Treshold exceeded by device type (in %)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (countIf(device_type, treshold_exceeded = 1)/countIf(device_type, treshold_exceeded = 0) * 100)as treshold_exceeded_percent,\n    device_type\nFROM telemetry\nGROUP BY device_type\nORDER BY treshold_exceeded_percent DESC\nLIMIT 5\n",
     "rawQuery": "SELECT     (countIf(device_type, treshold_exceeded = 1)/countIf(device_type, treshold_exceeded = 0) * 100)as treshold_exceeded_percent,     device_type FROM telemetry GROUP BY device_type ORDER BY treshold_exceeded_percent DESC LIMIT 5",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "TOP 5 - Treshold exceeded by department (in %)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (countIf(department, treshold_exceeded = 1) / countIf(device_type, treshold_exceeded = 0) * 100) as treshold_exceeded_percent,\n    department\nFROM telemetry\nGROUP BY department\nORDER BY treshold_exceeded_percent DESC\nLIMIT 5",
     "rawQuery": "SELECT     (countIf(department, treshold_exceeded = 1) / countIf(device_type, treshold_exceeded = 0) * 100) as treshold_exceeded_percent,     department FROM telemetry GROUP BY department ORDER BY treshold_exceeded_percent DESC LIMIT 5",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "Count telemetry by regions",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count() as requests,\n    region\nFROM telemetry\nGROUP BY region",
     "rawQuery": "SELECT     count() as requests,     region FROM telemetry GROUP BY region",
     "round": "0s"
    }
   ]
  }
 ]
}